# Generated by Django 2.1.4 on 2023-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishing',
            options={'verbose_name': '出版社信息', 'verbose_name_plural': '出版社信息'},
        ),
    ]
