# Generated by Django 2.1.7 on 2023-04-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=7, unique=True, verbose_name='车牌号')),
                ('driver', models.CharField(max_length=10, verbose_name='司机')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('remarks', models.CharField(blank=True, max_length=32, null=True, verbose_name='备注说明')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('dep_script', models.CharField(max_length=60, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=32, verbose_name='乘车人')),
                ('driver', models.CharField(max_length=10, verbose_name='司机')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('distance', models.IntegerField(verbose_name='公里数')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='车费')),
                ('drive_date', models.DateField(auto_now_add=True, null=True, verbose_name='乘车时间')),
                ('remark', models.CharField(max_length=100, verbose_name='乘车说明')),
                ('operator', models.CharField(max_length=32, verbose_name='输入人员')),
                ('approve_date', models.DateField(auto_now=True, null=True, verbose_name='审批时间')),
                ('approve_status', models.CharField(blank=True, choices=[('0', '未审批'), ('1', '审批通过')], max_length=1, null=True, verbose_name='审批状态')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fare.CarInfo')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fare.Department')),
            ],
        ),
        migrations.CreateModel(
            name='LogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='headimage', verbose_name='头像')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fare.Department')),
                ('user_obj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo')),
            ],
        ),
    ]
