# Generated by Django 2.1.4 on 2023-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_view', '0002_loguser_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='filedir', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='headimage', verbose_name='头像'),
        ),
    ]
