# Generated by Django 2.1.4 on 2023-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=32, verbose_name='权限代码')),
                ('url', models.CharField(max_length=128, verbose_name='URL Config Name')),
                ('name', models.CharField(max_length=120, verbose_name='Authority Description')),
            ],
            options={
                'verbose_name': 'Authority Table',
                'verbose_name_plural': 'Authority Table',
            },
        ),
    ]
