# Generated by Django 2.1.4 on 2023-03-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20230328_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_scrips',
            new_name='dep_script',
        ),
    ]
